# Generated by Django 5.2.7 on 2025-10-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sinotrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField()),
                ('phone_number', models.CharField()),
                ('payment_date', models.DateField()),
                ('end_date_rate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
