# Generated by Django 5.2.7 on 2026-01-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinotrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinotrack',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
