# Generated by Django 5.2.7 on 2026-01-31 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhereKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField()),
                ('phone_number', models.CharField()),
                ('comment', models.CharField(default='')),
                ('where_know', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.whereknow')),
            ],
        ),
    ]
