# Generated by Django 5.2.7 on 2026-01-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
