# Generated by Django 5.2.7 on 2025-10-13 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sinotrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField()),
                ('name', models.CharField()),
                ('model', models.CharField()),
                ('serial_number', models.CharField()),
                ('wheel_diameter', models.IntegerField()),
                ('rental_price', models.FloatField()),
                ('additional_rental_price', models.FloatField(default=0)),
                ('comments', models.CharField()),
                ('pledge', models.FloatField()),
                ('sinotrack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sinotrack.sinotrack')),
            ],
        ),
    ]
