# Generated by Django 5.2.7 on 2026-01-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='wheel_diameter',
            field=models.FloatField(),
        ),
    ]
