# Generated by Django 5.2.7 on 2026-01-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_alter_bike_wheel_diameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='additional_rental_price',
        ),
    ]
