# Generated by Django 5.2.7 on 2026-01-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_remove_bike__id_remove_bike_additional_rental_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='in_rent',
            field=models.BooleanField(default=False),
        ),
    ]
