# Generated by Django 5.2.7 on 2026-01-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_bike_in_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='pledge',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='rental_price',
        ),
    ]
